@startuml jamstack-prod

actor "User" <<Human>>

package prod {
  package go.pkg {
    package iishpc.app {
      package web {
        component "Application's shell" as appShell
        component "RESTful API" as api
      }
      package services{
        component "Service" as srv
      }
    }
  }
}

User --> appShell
appShell --> api
api --> srv

@enduml